### ISSUE TITLE
[Bug] Super key and rofi launcher

### ISSUE THREAD

**Issue by chris977** [archcraft-os/archcraft-fluxbox#1]
Super key opens rofi launcher only after several presses when there are opened windows in the current workspace.
I works as expected when no windows are opened, or when all the opened windows are minimized in the workspace.

My solution, in the keys file:
`Mod1 F1 :exec sleep 0.01; xdotool key --clearmodifiers Mod1 F1; {~/.fluxbox/rofi/bin/launcher}`

**Comment by adi1090x** [comment]
Yes, That happens.
It's not an issue with keybindings, It's how `ksuperkey` works in Fluxbox.
